(in-package :wildfire)

(defun test-model (state)
  (unless (and (zerop (getf state :speed)) (> (getf state :time) 5000))
    (return-from test-model))
  (let ((v (getf state :view))
        (ctr (getf state :center)))
    (labels ((matching-locs (pred)
               (iter (for x :from 0 :below (array-dimension v 0))
                     (nconcing (iter (for y :from 0 :below (array-dimension v 1))
                                     (for loc := (list x y))
                                     (when (funcall pred loc)
                                       (collect loc))))))
             (ref (loc)
               (apply #'aref v loc)))
      `(:target ,(random-elt (or (matching-locs (lambda (loc)
                                                  (and (second (ref loc))
                                                       (not (equal loc ctr)))))
                                 (matching-locs (lambda (loc)
                                                  (and (ref loc)
                                                       (>= (sqrt (apply #'+ (mapcar (rcurry #'expt 2)
                                                                                    (mapcar #'- loc))))
                                                           3))))))))))
